# App
spring.application.name=smarthire-service

# H2 Database
spring.datasource.url=jdbc:h2:mem:smarthiredb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server
server.port=8081

# Gemini AI API Key
gemini.api.key=AIzaSyAHQm_Nx5zAySg14tl2VBSRn13Uyo0bW_k

# File upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Actuator
management.endpoints.web.exposure.include=health,info